# Generated by Django 3.2.4 on 2021-07-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='chapter',
            name='supervisor_remarks',
            field=models.TextField(blank=True, default='--', null=True),
        ),
    ]
