# Generated by Django 3.2 on 2021-08-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210731_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='project_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='project_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
