# Generated by Django 3.2 on 2021-08-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210804_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='project_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='project_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
