# Generated by Django 3.2 on 2021-08-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210804_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=6)),
                ('student', models.CharField(max_length=50)),
                ('supervisor', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UploadChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.CharField(choices=[('Chapter One', 'Chapter One'), ('Chapter Two', 'Chapter Two'), ('Chapter Three', 'Chapter Three'), ('Chapter Four', 'Chapter Four'), ('Chapter Five', 'Chapter Five')], max_length=50)),
                ('chapter_file', models.FileField(upload_to='files')),
                ('student', models.CharField(max_length=50)),
                ('supervisor', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UploadProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=50)),
                ('project_title', models.CharField(max_length=100)),
                ('project_file', models.FileField(upload_to='files')),
                ('year', models.CharField(max_length=15)),
                ('supervisor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UploadProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_title', models.CharField(choices=[('Chapter One', 'Chapter One'), ('Chapter Two', 'Chapter Two'), ('Chapter Three', 'Chapter Three'), ('Chapter Four', 'Chapter Four'), ('Chapter Five', 'Chapter Five')], max_length=100)),
                ('proposal_file', models.FileField(upload_to='files')),
                ('student', models.CharField(max_length=50)),
                ('supervisor', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UploadTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=15)),
                ('supervisor', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='projectstatus',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='project_summary',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='requestmeeting',
            name='additional_informaton',
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=15),
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='time',
            field=models.CharField(default='12/12/2021', max_length=6),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='date',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='student',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='supervisor',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
    ]
