# Generated by Django 3.2 on 2021-08-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210804_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fullname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='fullname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
