# Generated by Django 3.2 on 2021-08-04 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20210804_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='username',
        ),
        migrations.AlterField(
            model_name='sendinvite',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sendinvite',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.supervisor'),
        ),
        migrations.AlterField(
            model_name='uploadchapter',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadchapter',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.supervisor'),
        ),
        migrations.AlterField(
            model_name='uploadproposal',
            name='proposal_file',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='uploadproposal',
            name='proposal_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadproposal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadproposal',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.supervisor'),
        ),
        migrations.AlterField(
            model_name='uploadtopic',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='uploadtopic',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.supervisor'),
        ),
    ]
