# Generated by Django 3.2 on 2021-08-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210805_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadchapter',
            name='chapter_file',
            field=models.FileField(upload_to='chapter'),
        ),
        migrations.AlterField(
            model_name='uploadchapter',
            name='student',
            field=models.CharField(default='CST/16/COM/00543', max_length=30),
        ),
        migrations.AlterField(
            model_name='uploadchapter',
            name='supervisor',
            field=models.CharField(default='Dr. F U Ambursa', max_length=30),
        ),
        migrations.AlterField(
            model_name='uploadproposal',
            name='proposal_file',
            field=models.FileField(default='-', upload_to='proposal'),
        ),
    ]
