# Generated by Django 3.2 on 2021-08-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210805_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadchapter',
            name='chapter_number',
            field=models.CharField(choices=[('Chapter One', 'Chapter One'), ('Chapter Two', 'Chapter Two'), ('Chapter Three', 'Chapter Three'), ('Chapter Four', 'Chapter Four'), ('Chapter Five', 'Chapter Five'), ('All Chapters', 'All Chapters')], max_length=50),
        ),
    ]
